// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resify.Services.ProductsAPI.Data;

#nullable disable

namespace Resify.Services.ProductsAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230704180520_InitialAdd")]
    partial class InitialAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Resify.Services.ProductsAPI.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("ProductCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8729dee-321c-4798-a906-dec7167ec277"),
                            ImageUrl = "nic",
                            Name = "Pizza",
                            Price = 13.12m,
                            ProductCategoryId = new Guid("50b399c5-4b4f-4568-b3ce-2a339e445f36"),
                            RestaurantId = new Guid("5141148d-2d80-4c88-ace3-606ec8583143")
                        },
                        new
                        {
                            Id = new Guid("63fdf0b2-ffa0-4f4c-8a15-f826951826e1"),
                            ImageUrl = "nic",
                            Name = "Spaghetti",
                            Price = 23.50m,
                            ProductCategoryId = new Guid("50b399c5-4b4f-4568-b3ce-2a339e445f36"),
                            RestaurantId = new Guid("5141148d-2d80-4c88-ace3-606ec8583143")
                        },
                        new
                        {
                            Id = new Guid("277ff66d-fd38-4a8f-92aa-76632259308b"),
                            ImageUrl = "nic",
                            Name = "Pierogi",
                            Price = 30.50m,
                            ProductCategoryId = new Guid("2a61304d-3308-45c6-805a-42fa4a5dfaac"),
                            RestaurantId = new Guid("5141148d-2d80-4c88-ace3-606ec8583143")
                        },
                        new
                        {
                            Id = new Guid("a3a1eb98-717c-4979-a3c3-7abdc0d3cc05"),
                            ImageUrl = "nic",
                            Name = "Hamburger",
                            Price = 38.50m,
                            ProductCategoryId = new Guid("2bcb40ca-9beb-4f18-a4d2-89395e9e3e4b"),
                            RestaurantId = new Guid("945969d0-3883-466b-b632-c20fdf8a19bc")
                        },
                        new
                        {
                            Id = new Guid("d153b070-74a7-42ed-9c47-7bbae74d81c3"),
                            ImageUrl = "nic",
                            Name = "Frytki",
                            Price = 8.99m,
                            ProductCategoryId = new Guid("2bcb40ca-9beb-4f18-a4d2-89395e9e3e4b"),
                            RestaurantId = new Guid("945969d0-3883-466b-b632-c20fdf8a19bc")
                        },
                        new
                        {
                            Id = new Guid("d262ed04-92e4-4f9a-bf20-cfc2a72f76e9"),
                            ImageUrl = "nic",
                            Name = "Pizza",
                            Price = 45m,
                            ProductCategoryId = new Guid("2bcb40ca-9beb-4f18-a4d2-89395e9e3e4b"),
                            RestaurantId = new Guid("945969d0-3883-466b-b632-c20fdf8a19bc")
                        });
                });

            modelBuilder.Entity("Resify.Services.ProductsAPI.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50b399c5-4b4f-4568-b3ce-2a339e445f36"),
                            Name = "Włoskie"
                        },
                        new
                        {
                            Id = new Guid("2a61304d-3308-45c6-805a-42fa4a5dfaac"),
                            Name = "Polskie"
                        },
                        new
                        {
                            Id = new Guid("2bcb40ca-9beb-4f18-a4d2-89395e9e3e4b"),
                            Name = "Amerykańskie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
